# Generated by Django 4.2.1 on 2023-05-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_listing_id_contact_realtor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='realtor_email',
        ),
    ]
