bedroom_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10
  }

price_choices = {
    '100000':'£100,000',
    '200000':'£200,000',
    '300000':'£300,000',
    '400000':'£400,000',
    '500000':'£500,000',
    '600000':'£600,000',
    '700000':'£700,000',
    '800000':'£800,000',
    '900000':'£900,000',
    '1000000':'£1M+',
}

county_choices = {
    'ABD': 'Aberdeenshire',
    'ABE': 'Aberdeen City',
    'AGB': 'Argyll and Bute',
    'AGY': 'Isle of Anglesey',
    'ANS': 'Angus',
    'ANT': 'Antrim',
    'ARD': 'Ards',
    'ARM': 'Armagh',
    'BAS': 'Bath',
    'BBD': 'Blackburn',
    'BDF': 'Bedford',
    'BDG': 'Barking and Dagenham',
    'BEN': 'Brent',
    'BEX': 'Bexley',
    'BFS': 'Belfast',
    'BGE': 'Bridgend',
    'BGW': 'Blaenau Gwent',
    'BIR': 'Birmingham',
    'BKM': 'Buckinghamshire',
    'BLA': 'Ballymena',
    'BMH': 'Bournemouth',
    'BNB': 'Banbridge',
    'BNE': 'Barnet',
    'BNH': 'Brighton and Hove',
    'BNS': 'Barnsley',
    'BOL': 'Bolton',
    'BPL': 'Blackpool',
    'BRC': 'Bracknell Forest',
    'BRD': 'Bradford',
    'BRY': 'Bromley',
    'BST': 'Bristol, City of',
    'BUR': 'Bury',
    'CAM': 'Cambridgeshire',
    'CAY': 'Caerphilly',
    'CBF': 'Central Bedfordshire',
    'CGN': 'Ceredigion',
    'CGV': 'Craigavon',
    'CHE': 'Cheshire',
    'CKF': 'Carrickfergus',
    'CLK': 'Clackmannanshire',
    'CLR': 'Coleraine',
    'CMA': 'Cumbria',
    'CMD': 'Camden',
    'CMN': 'Carmarthenshire',
    'CON': 'Cornwall',
    'COV': 'Coventry',
    'CRF': 'Cardiff',
    'CRY': 'Croydon',
    'CSR': 'Castlereagh',
    'CWY': 'Conwy',
    'DAL': 'Darlington',
    'DBY': 'Derbyshire',
    'DEN': 'Denbighshire',
    'DEV': 'Devon',
    'DGN': 'Dungannon and South Tyrone',
    'DGY': 'Dumfries and Galloway',
    'DNC': 'Doncaster',
    'DND': 'Dundee City',
    'DOR': 'Dorset',
    'DOW': 'Down',
    'DRY': 'Derry and Strabane',
    'DUD': 'Dudley',
    'DUR': 'Durham, County',
    'EAL': 'Ealing',
    'EAY': 'East Ayrshire',
    'EDH': 'Edinburgh, City of',
    'EDU': 'East Dunbartonshire',
    'ELN': 'East Lothian',
    'ELS': 'Eilean Siar',
    'ENF': 'Enfield',
    'ERW': 'East Renfrewshire',
    'ERY': 'East Riding of Yorkshire',
    'ESS': 'Essex',
    'ESX': 'East Sussex',
    'FAL': 'Falkirk',
    'FER': 'Fermanagh and Omagh',
    'FIF': 'Fife',
    'FLN': 'Flintshire',
    'GAT': 'Gateshead',
    'GLG': 'Glasgow City',
    'GLS': 'Gloucestershire',
    'GRE': 'Greenwich',
    'GSY': 'Guernsey',
    'GWN': 'Gwynedd',
    'HAL': 'Halton',
    'HAM': 'Hampshire',
    'HAV': 'Havering',
    'HCK': 'Hackney',
    'HEF': 'Herefordshire, County of',
    'HIL': 'Hillingdon',
    'HLD': 'Highland',
    'HMF': 'Hammersmith and Fulham',
    'HNS': 'Hounslow',
    'HPL': 'Hartlepool',
    'HRT': 'Hertfordshire',
    'HRW': 'Harrow',
    'HRY': 'Haringey',
    'IOS': 'Isles of Scilly',
    'IOW': 'Isle of Wight',
    'ISL': 'Islington',
    'IVC': 'Inverclyde',
    'KEC': 'Kensington and Chelsea',
    'KEN': 'Kent',
    'KHL': 'Kingston upon Hull, City of',
    'KIR': 'Kirklees',
    'KTT': 'Kingston upon Thames',
    'KWL': 'Knowsley',
    'LAN': 'Lancashire',
    'LBC': 'Lisburn and Castlereagh',
    'LBH': 'Lambeth',
    'LCE': 'Leicester',
    'LDS': 'Leeds',
    'LEC': 'Leicestershire',
    'LEW': 'Lewisham',
    'LIN': 'Lincolnshire',
    'LIV': 'Liverpool',
    'LMV': 'Limavady',
    'LND': 'London, City of',
    'LRN': 'Larne',
    'LSB': 'Lisburn',
    'LUT': 'Luton',
    'MAN': 'Manchester',
    'MDB': 'Middlesbrough',
    'MDW': 'Medway',
    'MFT': 'Magherafelt',
    'MIK': 'Milton Keynes',
    'MLN': 'Midlothian',
    'MON': 'Monmouthshire',
    'MRT': 'Merton',
    'MRY': 'Moray',
    'MTY': 'Merthyr Tydfil',
    'MYL': 'Moyle',
    'NAY': 'North Ayrshire',
    'NBL': 'Northumberland',
    'NDN': 'North Down',
    'NEL': 'North East Lincolnshire',
    'NET': 'Newcastle upon Tyne',
    'NFK': 'Norfolk',
    'NGM': 'Nottingham',
    'NLK': 'North Lanarkshire',
    'NLN': 'North Lincolnshire',
    'NSM': 'North Somerset',
    'NTH': 'Northamptonshire',
    'NTL': 'Neath Port Talbot',
    'NTT': 'Nottinghamshire',
    'NTY': 'North Tyneside',
    'NWM': 'Newham',
    'NWP': 'Newport',
    'NYK': 'North Yorkshire',
    'NYM': 'Newry, Mourne and Down',
    'OLD': 'Oldham',
    'OMH': 'Omagh',
    'ORK': 'Orkney Islands',
    'OXF': 'Oxfordshire',
    'PEM': 'Pembrokeshire',
    'PKN': 'Perth and Kinross',
    'PLY': 'Plymouth',
    'POL': 'Poole',
    'POR': 'Portsmouth',
    'POW': 'Powys',
    'PTE': 'Peterborough',
    'RCC': 'Redcar and Cleveland',
    'RCH': 'Rochdale',
    'RCT': 'Rhondda Cynon Taf',
    'RDG': 'Reading',
    'RFW': 'Renfrewshire',
    'RIC': 'Richmond upon Thames',
    'ROT': 'Rotherham',
    'RUT': 'Rutland',
    'SAW': 'Sandwell',
    'SAY': 'South Ayrshire',
    'SCB': 'Scottish Borders, The',
    'SCT': 'Scotland',
    'SFK': 'Suffolk',
    'SFT': 'Sefton',
    'SGC': 'South Gloucestershire',
    'SHF': 'Sheffield',
    'SHN': 'St. Helens',
    'SHR': 'Shropshire',
    'SKP': 'Stockport',
    'SLF': 'Salford',
    'SLG': 'Slough',
    'SLK': 'South Lanarkshire',
    'SND': 'Sunderland',
    'SOL': 'Solihull',
    'SOM': 'Somerset',
    'SOS': 'Southend-on-Sea',
    'SRY': 'Surrey',
    'STB': 'Strabane',
    'STE': 'Stoke-on-Trent',
    'STG': 'Stirling',
    'STH': 'Southampton',
    'STN': 'Sutton',
    'STS': 'Staffordshire',
    'STT': 'Stockton-on-Tees',
    'STY': 'South Tyneside',
    'SWA': 'Swansea',
    'SWD': 'Swindon',
    'SWK': 'Southwark',
    'TAM': 'Tameside',
    'TFW': 'Telford and Wrekin',
    'THR': 'Thurrock',
    'TOB': 'Torbay',
    'TOF': 'Torfaen',
    'TRF': 'Trafford',
    'TWH': 'Tower Hamlets',
    'TYR': 'Tyrone',
    'VGL': 'Vale of Glamorgan, The',
    'WKF': 'Wakefield',
    'WLL': 'Walsall',
    'WLN': 'West Lothian',
    'WLS': 'Wales',
    'WLV': 'Wolverhampton',
    'WND': 'Wandsworth',
    'WNM': 'Windsor and Maidenhead',
    'WOK': 'Wokingham',
    'WOR': 'Worcestershire',
    'WRL': 'Wirral',
    'WRT': 'Warrington',
    'WRX': 'Wrexham',
    'WSM': 'Westminster',
    'WSX': 'West Sussex',
    'YOR': 'York'
}